### ISSUE TITLE
xpath: Cannot select attribute? 

### ISSUE THREAD

**Issue by SuperKenVery** [James-LG/Skyscraper#15]
For example, 

document:
```html
<input name="hi" id="in"></input>
```
I hope
```xpath
//*[@id="in"]//@name
```
to return a `Vec` containing `hi`, but in fact it returns an empty `Vec`.

This syntax works in python `lxml`, so I guess it's a problem with this library?

**Comment by James-LG** [comment]
Yes, attribute selection with XPath has not yet been implemented, but it is on my todo list.

In the meantime you can just get the node with XPath and use the library to retrieve the attributes. See the docs [here](https://docs.rs/skyscraper/latest/skyscraper/html/struct.DocumentNode.html#method.get_attributes).
