### ISSUE TITLE
Missing whitespace characters in text

### ISSUE THREAD

**Issue by ArtemGolovko** [James-LG/Skyscraper#26]
Whitespace character stripped from element text. Characters such as line feed and carriage return are missing in text.

Because of that, I can't use your library for my use case.

**Comment by James-LG** [comment]
The text methods were made to match browsers, but they ignore most whitespace which can be confusing.

I'll create/update methods to match [lxml](https://lxml.de/) instead since that is a very popular XPath library that most users are probably already familiar with.
