### ISSUE TITLE
Add Support for /@href

### ISSUE THREAD

**Issue by DioxusGrow** [James-LG/Skyscraper#36]
Please add support for /@href. As I collect links in almost every parser, the lack of this feature in the crate will prevent me from using it.

**Comment by James-LG** [comment]
Yes this is already supported. I have improved the docs in [0.7.0-beta.0](https://docs.rs/skyscraper/0.7.0-beta.0/skyscraper/xpath/index.html#example-get-links-with-the-href-xpath-step).
